### ISSUE TITLE
issue with coords

### ISSUE THREAD

**Issue by st860923** [pedr0fontoura/gtav-audio-occlusion#2]
https://github.com/snakewiz/gtav-audio-occlusion/blob/6cb7d2a747f120468e0b441db6b86f3543847f1d/src/core/classes/audioGameData.ts#L58

should be like 
z: this.interior.entitiesExtentsMax.z - this.interior.entitiesExtentsMin.z,

**Comment by snakewiz** [comment]
Thanks for reporting, fixed on d17deba4c3d784cd4c8e89a1628dd0beb2d61b38.
