### ISSUE TITLE
Can Only run for a single Map

### ISSUE THREAD

**Issue by junior99au** [pedr0fontoura/gtav-audio-occlusion#21]
So when you use the tool to make another set of audio occlusions for another map so for example I have:
MLO - Warehouse
MLO - Mafia

And we make occlusions for Warehouse and run it they work, then we make it for Mafia and start that resource 2nd in the config, Occlusions will work for Warehouse but not mafia, if we disable warehouse and its occlusions then occlusions will work for Mafia. Is there a way to run both sets? Even if its something that needs to be set manually outside of the tool?

**Comment by benzon** [comment]
@junior99au how did you solve this if you solved it ?
