### ISSUE TITLE
Audio routing issue with some custom MLO's

### ISSUE THREAD

**Issue by AdrineX** [pedr0fontoura/gtav-audio-occlusion#7]
I've generated over 30 interiors without any issues with this tool, but with some interiors I got some kind of routing issue, like for example: Audio travels correctly from limbo to room it's linked with but after whatever room I'm in audio stops travelling between rooms. This has happened on +10 custom MLO's we have on our server and can't seem to figure it out why is it doing that. I've tried multiple different portal flags if it's related to that, checked multiple times if the attached entities are linked correctly to portals etc etc.

I'm pretty sure there are people facing same problems as I am. Also I'm pretty confident the issue is related to algorithm that generates paths between rooms.

I can provide files to sort this issue out when needed.

**Comment by pedr0fontoura** [comment]
Are you editing the room linking on the tool for the interiors that have this issue? That probably could break the audio routing

**Comment by AdrineX** [comment]
> Are you editing the room linking on the tool for the interiors that have this issue? That probably could break the audio routing

No, I usually just run the tool like it suggests the linked rooms.

**Comment by pedr0fontoura** [comment]
Please DM me one of those mlo's, so I can take a look at it. My Discord is snakewiz#5463
