### ISSUE TITLE
Crash everytime I goto generate

### ISSUE THREAD

**Issue by ghost** [pedr0fontoura/gtav-audio-occlusion#8]
Hey, i am having a problem with this tool crashing everytime I goto generate files using the "+" buttons, I import the ytyp and ymap .xml's and select an output, then clicking either generate will give the tool a blank screen and give the error in console in the below SS

I have tried both release build and latest commits with no luck

please help, would really love to get this working, thank you

https://i.gyazo.com/d1dab2698a467680760fb9c9cb32b787.png

**Comment by pedr0fontoura** [comment]
Could you please attach the files that cause this issue?

**Comment by ghost** [comment]
Hey, cheers for the really quick reply, its pretty much any I've attempted, but I've tried spending more time today trying to understand audio occlusions, so I'll attach the .xml's from Gabz new PDM

**File removed**

**Comment by ghost** [comment]
Sorry, but heres more info from console

https://i.gyazo.com/c3e5d300cb58b582004df1161fba7987.png

**Comment by pedr0fontoura** [comment]
Already downloaded the files, i'll take a look soon.

**Comment by pushkart2** [comment]
I am having the same issue as well.. any update?

**Comment by pushkart2** [comment]
I though it was an issue with my client or something but when I used the xml files that Nikez updated on his git.. it worked perfectly fine
