### ISSUE TITLE
Cannot read property 'isDoor' of undefined

### ISSUE THREAD

**Issue by tovermannetje** [pedr0fontoura/gtav-audio-occlusion#9]
Hello i get the error message: "Uncaught (in promise) Error: Error invoking remote method 'generateAudioOcclusion': TypeError: Cannot read property 'isDoor' of undefined
    at EventEmitter.i.invoke (electron/js2c/renderer_init.js:73)"

When i try to generate the audioOcclusion. I've tried multiple MLO's made by my friend but the same error keeps popping up.

https://i.imgur.com/AWQW6Oi.png

**Comment by jutzy** [comment]
Im also receiving something similar to this.

Its just the one ytyp/ymap that its occurring on

> Error occurred in handler for 'generateAudioOcclusion': TypeError: Cannot read property 'isDoor' of undefined
>     at d:\gtav-audio-occlusion\dist\main.js:2:123446
>     at Array.map (<anonymous>)
>     at d:\gtav-audio-occlusion\dist\main.js:2:123412
>     at Array.map (<anonymous>)
>     at t.value (d:\gtav-audio-occlusion\dist\main.js:2:123370)
>     at new t (d:\gtav-audio-occlusion\dist\main.js:2:122857)
>     at e.value (d:\gtav-audio-occlusion\dist\main.js:2:129664)
>     at electron/js2c/browser_init.js:201:579
>     at Object.<anonymous> (electron/js2c/browser_init.js:161:10005)
>     at Object.emit (events.js:315:20)
